use modelcarsdb;

-- TASK 1 - EMPLOYEE DATA ANALYSIS

-- 1.) Total number of employees in the company
SELECT COUNT(*) AS total_employees
FROM employees;

-- 2.) Display all employees’ full information
SELECT *
FROM employees;

-- 3.) Count of employees for each job title
SELECT jobTitle, COUNT(*) AS employee_count
FROM employees
GROUP BY jobTitle;

-- 4.) List employees who do not report to anyone
SELECT employeeNumber, firstName, lastName, jobTitle
FROM employees
WHERE reportsTo IS NULL;

-- TASK 5: Calculate total sales generated by each sales representative
SELECT e.employeeNumber, e.firstName, e.lastName, SUM(od.quantityOrdered * od.priceEach) AS total_sales
FROM employees e 
JOIN customers c ON c.salesRepEmployeeNumber = e.employeeNumber
JOIN orders o ON o.customerNumber = c.customerNumber
JOIN orderdetails od ON od.orderNumber = o.orderNumber
GROUP BY e.employeeNumber, e.firstName, e.lastName
ORDER BY total_sales DESC;

-- TASK 6: Find the most profitable sales representative based on total sales
SELECT e.employeeNumber, e.firstName, e.lastName, SUM(od.quantityOrdered * od.priceEach) AS total_sales, 
	SUM(od.quantityOrdered * p.buyPrice) AS total_cost, (SUM(od.quantityOrdered * od.priceEach) - SUM(od.quantityOrdered * p.buyPrice)) AS profit
FROM employees e
JOIN customers c ON c.salesRepEmployeeNumber = e.employeeNumber
JOIN orders o ON o.customerNumber = c.customerNumber
JOIN orderdetails od ON od.orderNumber = o.orderNumber
JOIN products p ON p.productCode = od.productCode
GROUP BY e.employeeNumber, e.firstName, e.lastName
ORDER BY profit DESC;

-- TASK 7: Employees who sold more than the average sales in their office

-- STEP 1: Calculate total sales for each employee
SELECT e.employeeNumber, e.firstName, e.lastName, e.officeCode, emp_sales.total_sales
FROM employees e
JOIN (
    SELECT e1.employeeNumber, e1.officeCode, SUM(od1.quantityOrdered * od1.priceEach) AS total_sales
    FROM employees e1
    JOIN customers c1 ON c1.salesRepEmployeeNumber = e1.employeeNumber
    JOIN orders o1 ON o1.customerNumber = c1.customerNumber
    JOIN orderdetails od1 ON od1.orderNumber = o1.orderNumber
    GROUP BY e1.employeeNumber, e1.officeCode
) AS emp_sales ON e.employeeNumber = emp_sales.employeeNumber

-- STEP 2: Compare each employee's sales with the average sales in their office
WHERE emp_sales.total_sales > (
    SELECT AVG(sales.total_sales)
    FROM (
        SELECT e2.officeCode, e2.employeeNumber, SUM(od2.quantityOrdered * od2.priceEach) AS total_sales
        FROM employees e2
        JOIN customers c2 ON c2.salesRepEmployeeNumber = e2.employeeNumber
        JOIN orders o2 ON o2.customerNumber = c2.customerNumber
        JOIN orderdetails od2 ON od2.orderNumber = o2.orderNumber
        GROUP BY e2.employeeNumber, e2.officeCode
    ) AS sales
    WHERE sales.officeCode = emp_sales.officeCode
);
